"""empty message

Revision ID: 07cb8edb99f3
Revises: 5eb33c3a38a3
Create Date: 2024-08-07 13:36:25.450572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07cb8edb99f3'
down_revision = '5eb33c3a38a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mascota', schema=None) as batch_op:
        batch_op.alter_column('favorito_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('favorito_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('favorito_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('mascota', schema=None) as batch_op:
        batch_op.alter_column('favorito_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
