"""empty message

Revision ID: 148781dd5e43
Revises: 0eeeec6f719c
Create Date: 2024-08-15 18:37:17.440349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '148781dd5e43'
down_revision = '0eeeec6f719c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mascota', schema=None) as batch_op:
        batch_op.alter_column('coord_x',
               existing_type=sa.NUMERIC(precision=3, scale=6),
               type_=sa.Numeric(precision=10, scale=6),
               existing_nullable=True)
        batch_op.alter_column('coord_y',
               existing_type=sa.NUMERIC(precision=3, scale=6),
               type_=sa.Numeric(precision=10, scale=6),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mascota', schema=None) as batch_op:
        batch_op.alter_column('coord_y',
               existing_type=sa.Numeric(precision=10, scale=6),
               type_=sa.NUMERIC(precision=3, scale=6),
               existing_nullable=True)
        batch_op.alter_column('coord_x',
               existing_type=sa.Numeric(precision=10, scale=6),
               type_=sa.NUMERIC(precision=3, scale=6),
               existing_nullable=True)

    # ### end Alembic commands ###
