"""empty message

Revision ID: 49533eefd2f2
Revises: 789a4710126e
Create Date: 2024-08-09 14:45:36.592885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49533eefd2f2'
down_revision = '789a4710126e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('localidad', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('localidad', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=25),
               existing_nullable=False)

    # ### end Alembic commands ###
