"""empty message

Revision ID: 750715863bf6
Revises: 971e9ec5bee5
Create Date: 2024-08-12 19:41:24.708306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '750715863bf6'
down_revision = '971e9ec5bee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mascota', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departamento_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'departamento', ['departamento_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mascota', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('departamento_id')

    # ### end Alembic commands ###
