"""empty message

Revision ID: 971e9ec5bee5
Revises: b6c98daf0e31
Create Date: 2024-08-12 18:08:35.375903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '971e9ec5bee5'
down_revision = 'b6c98daf0e31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mascota', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raza_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'raza', ['raza_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mascota', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('raza_id')

    # ### end Alembic commands ###
