"""empty message

Revision ID: b6c98daf0e31
Revises: e269e8b6ce6d
Create Date: 2024-08-12 16:17:53.836109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6c98daf0e31'
down_revision = 'e269e8b6ce6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_localidad_id_fkey', type_='foreignkey')
        batch_op.drop_column('localidad_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('localidad_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('user_localidad_id_fkey', 'localidad', ['localidad_id'], ['id'])

    # ### end Alembic commands ###
