"""empty message

Revision ID: e269e8b6ce6d
Revises: 6e90723bfa25
Create Date: 2024-08-12 16:03:07.665892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e269e8b6ce6d'
down_revision = '6e90723bfa25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('localidad_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('localidad_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
