"""empty message

Revision ID: e945d9b67c1a
Revises: 43d92258f705
Create Date: 2024-08-06 15:56:38.525475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e945d9b67c1a'
down_revision = '43d92258f705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mascota', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('fecha_perdido',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mascota', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('fecha_perdido',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
